apiVersion: v1
kind: Service
metadata:
  name: matterircd-ss
spec:
  selector:
    app: matterircd
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: matterircd
spec:
  selector:
    app: matterircd
  ports:
  - name: irc
    targetPort: 6667
    port: 6667
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: matterircd
spec:
  serviceName: matterircd-ss
  template:
    metadata:
      labels:
        app: matterircd
    spec:
      containers:
      - name: matterircd
        image: 42wim/matterircd
        args: ["-bind", "0.0.0.0:6667"]
        ports:
        - containerPort: 6667
          name: irc
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
